version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  test:
    docker:
      - image: cimg/node:22.6.0-browsers

    steps:
      - checkout
      - browser-tools/install-browser-tools
      - restore_cache:
          keys:
            - npm-cache-v1-{{ checksum "package-lock.json" }}
            - npm-cache-v1-
      - run:
          name: Package install
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: |
            npm run test:all

workflows:
  test-and-coverage:
    jobs:
      - test
