name: CI without Nx

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 22
      #     cache: 'npm'

      # - run: npm ci
      #   name: Install dependencies

      # - run: npm run build-and-test
      #   name: Test and Build
